version: '3'

services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mypassword
            MYSQL_DATABASE: diploma
        ports:
            - "3306:3306"

    app:
        build: .
        image: diploma_image
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
